//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomer
    {
        public tblCustomer()
        {
            this.tblSells = new HashSet<tblSell>();
            this.tblInvoiceDetails = new HashSet<tblInvoiceDetail>();
        }
    
        public int CustomerID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FatherName { get; set; }
        public string Email { get; set; }
        public string ContactNo { get; set; }
        public string CNIC { get; set; }
        public string U_FileName { get; set; }
        public string U_FilePath { get; set; }
    
        public virtual ICollection<tblSell> tblSells { get; set; }
        public virtual ICollection<tblInvoiceDetail> tblInvoiceDetails { get; set; }
    }
}
