//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblpurchase
    {
        public tblpurchase()
        {
            this.tblPurchaseDetails = new HashSet<tblPurchaseDetail>();
        }
    
        public int PurchaseID { get; set; }
        public Nullable<int> VendorID { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<int> ShipmentID { get; set; }
        public Nullable<int> ShipmentTotal { get; set; }
        public Nullable<int> AmountPaid { get; set; }
    
        public virtual ICollection<tblPurchaseDetail> tblPurchaseDetails { get; set; }
        public virtual tblVendor tblVendor { get; set; }
    }
}
