//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct
    {
        public tblProduct()
        {
            this.tblPurchaseDetails = new HashSet<tblPurchaseDetail>();
            this.tblStocks = new HashSet<tblStock>();
            this.tblStockDetails = new HashSet<tblStockDetail>();
            this.tblSellDetails = new HashSet<tblSellDetail>();
            this.tblSellDetailtempories = new HashSet<tblSellDetailtempory>();
            this.tblInvoiceDetails = new HashSet<tblInvoiceDetail>();
        }
    
        public int ProductID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string ProductName { get; set; }
        public string Model { get; set; }
        public string IMEI1 { get; set; }
        public string IMEI2 { get; set; }
        public string IMEI3 { get; set; }
        public string IMEI4 { get; set; }
        public string PurchasePrice { get; set; }
        public string SalePrice { get; set; }
        public Nullable<bool> IsNew { get; set; }
    
        public virtual tblCompany tblCompany { get; set; }
        public virtual tblProductCategory tblProductCategory { get; set; }
        public virtual ICollection<tblPurchaseDetail> tblPurchaseDetails { get; set; }
        public virtual ICollection<tblStock> tblStocks { get; set; }
        public virtual ICollection<tblStockDetail> tblStockDetails { get; set; }
        public virtual ICollection<tblSellDetail> tblSellDetails { get; set; }
        public virtual ICollection<tblSellDetailtempory> tblSellDetailtempories { get; set; }
        public virtual ICollection<tblInvoiceDetail> tblInvoiceDetails { get; set; }
    }
}
