//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPatient
    {
        public tblPatient()
        {
            this.tblBillings = new HashSet<tblBilling>();
        }
    
        public int PatientID { get; set; }
        public string Patient_Name { get; set; }
        public int Room_No { get; set; }
        public string Ward { get; set; }
    
        public virtual ICollection<tblBilling> tblBillings { get; set; }
    }
}
