//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSell
    {
        public tblSell()
        {
            this.tblStockDetails = new HashSet<tblStockDetail>();
            this.tblSellDetails = new HashSet<tblSellDetail>();
        }
    
        public int SellID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<System.DateTime> SellDate { get; set; }
        public Nullable<int> AmountPaid { get; set; }
    
        public virtual tblCustomer tblCustomer { get; set; }
        public virtual ICollection<tblStockDetail> tblStockDetails { get; set; }
        public virtual ICollection<tblSellDetail> tblSellDetails { get; set; }
    }
}
